openapi: 3.0.2
info:
  version: 1.0.0
  title: EBANX Payment - 3DS 2.0
  termsOfService: 'https://example.com/terms/'
  contact:
    email: integration@ebanx.com
    url: 'http://www.ebanx.com'
  x-logo:
    url: 'https://mrcsvg.github.io/EBANX-api-reference/assets/ebanx-logo-vector.svg'
  description:
    $ref: md_descriptions/test.md

externalDocs:
  description: More documentation about EBANX is also available in our developers portal
  url: 'https://developers.ebanx.com'
tags:
  - name: Payment with 3DS
    description: Example 3DS 2.0 Payment
servers:
  - url: 'https://api.ebanxpay.com/'
  - url: 'https://sandbox.ebanxpay.com/'
paths:
  /ws/direct:
    $ref: paths/direct.yaml
components:
  securitySchemes:
    integration_key:
      type: apiKey
      in: query  # gambiarra, mas funcionou
      name: integration_key
